### ISSUE TITLE
Add a `-v`/`--verbose` option

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [neurospin/neuro-forge#18]
And have `neuro-forge build` pass the option to `rattler-build`, I need it to debug `rattler-build`.

If I pass `-v` multiple times, it should be passed multiple times to `rattler-build` too.

**Comment by DimitriPapadopoulos** [comment]
Froget it: `rattler-build -v -v -v` doesn't really show anything 🙁

**Comment by sapetnioc** [comment]
Should we close the issue then ?
