### ISSUE TITLE
anatomist requires matplotlib==3.4.3

### ISSUE THREAD

**Issue by sapetnioc** [neurospin/neuro-forge#5]
Anatomist package has a dependency on matplotlib==3.4.3 inherited from BrainVISA container creation. This dependency imposes Python == 3.10. Therefore, it is not possible to make packages for Python 3.11 and Python 3.12. Do anyone knows if this matplotlib version is still a strong requirement ?

**Comment by denisri** [comment]
I don't remember any strong issue with matplotlib version. I guess this fixed version was a precaution to have consistent run/dev containers for the same containers versions in casa-distro.
If you want to test with different versions, you can run anatomist, load an image and use windows of types matplotlib-profile, matplotlib-histogram, values pot, stats plot, and check that they open correctly, and display things...

**Comment by sapetnioc** [comment]
I removed the version of matplotlib and was able to build with Python 3.11 (not able to compile with 3.12 yet) and test some matplotlib views in Anatomist.
